### PR TITLE
Vue 2.7 refresh

### PR DESCRIPTION
**Pull request by jrgm**
Hi,

First, thanks for writing this app. It's pretty nice!

Anyways, I tried building this with node18, and it fails to compile. After dropping back to node14, it would compile, but only if I didn't change package-lock.json. So, I eventually did a refresh, fixed some eslint bugs, and everything is update, using vue 2.7.14 and @fortawesome/vue-fontawesome@2.

The icons are a little larger with this version though. I'm not so familiar with FA, but maybe I'll look more at this change.

You also might not want the automatic lint changes. I so, I can drop that last commit from this PR.

Cheers,
John

### CODE REVIEW

**Comment by jrgm** [comment]
Hmm, so neflify checks failed as @vue/cli-service@5.0.8 requires node >= 12, and those checks are running on node 10. Oops.

**Comment by tfeldmann** [comment]
Thanks for the PR! I added a `.nvmrc` to pin node to v12.

**Comment by tfeldmann** [comment]
Oops, I was a bit fast with this one. The icons are much too big now. Care to investigate?

**Comment by jrgm** [comment]
> Oops, I was a bit fast with this one. The icons are much too big now. Care to investigate?

I filed an updated [PR](https://github.com/tfeldmann/fretty.app/pull/8), which corrects the icon size problem (pending a real fix in fa).

**Pull request merged**
